services:
  backend:
    build:
      context: .
    volumes:
      - ./backend/:/app
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=info
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload